config/routes.rb
FlyShortcutRails::Application.routes.draw do
  match 'flights' => 'flights#index', as: :flights
  match 'filter' => 'flights#filter', as: :filter
  match 'visited' => 'flights#visited', as: :visited
  match 'about_us' => 'pages#about_us', as: :about_us
  match 'fbtest' => 'pages#fbtest', as: :fbtest
  match 'best_roundtrips' => 'pages#best_roundtrips', as: :best_roundtrips
  match 'offsite_flight' => 'offsite_flights#redirect', as: :offsite_flight
  match 'ga_test' => 'pages#ga_test', as: :ga_test
  match 'signups' => 'pages#signups', as: :signups
  post 'donate' => 'donations#donate', as: :donate
  get "routes-to-scrape" => "flights#routes_to_scrape", :as => :routes_to_scrape
  match 'blog' => 'blogs#index', as: :blogs
  get 'blog/:slug' => 'blogs#show', as: :blog
  resources :users, :only => [:create]
  resources :routes, :except => [:show]
  root :to => 'pages#index'

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    page = params[:page].to_i || 0
    client = Tumblr::Client.new
    tumblr_posts = client.posts("flyshortcut.tumblr.com", :filter => "text", :offset => page * 20)
    @posts = tumblr_posts["posts"]
    @user = User.new
    @airports = Airport.all.map { |airport| airport.name }.unshift("(Desired departure airport)")
  end

  def show
    client = Tumblr::Client.new
    @post = client.posts("flyshortcut.tumblr.com", :tag => params[:slug])["posts"][0]
    @user = User.new
    @airports = Airport.all.map { |airport| airport.name }.unshift("(Desired departure airport)")
  end
end

app/views/blogs/index.html.slim
#fb-root
javascript:
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=651908141502421";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

css:
  html, body {
    background-color: white !important;
  }

.container
  .row
    .col-md-3.col-xs-12
      .row.header-column
        .col-xs-12 style="text-align: center;"
          = render 'layouts/header'
          = render 'layouts/left_email'
          / = render 'layouts/left_link_to_flights'
    .col-md-8.col-md-offset-1.col-xs-12
      .posts-container
        - @posts.each do |post|
          h3 style="font-weight: bold;"
            = link_to(post["title"].html_safe, blog_path(post["slug"]))
          h4
            small
              = format_tumblr_date(post["date"])
          p
            = truncate_html(post["body"], length: 300, omission: '...')

app/views/blogs/show.html.slim
- content_for :head do
  meta property="og:url" content="#{request.original_url}"
  meta property="og:image" content="#{find_first_image(@post["body"])}"
  meta property="og:title" name="title" content="#{@post["title"]}"
  meta property="og:description" name="description" content="#{truncate_html(strip_tags(@post["body"]), length: 300, omission: '...')}"

#fb-root
javascript:
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=651908141502421";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

css:
  html, body {
    background-color: white !important;
  }

.container
  .row
    .col-md-3.col-xs-12
      .row.header-column
        .col-xs-12 style="text-align: center;"
          = render 'layouts/header'
          = render 'layouts/left_email'
          / = render 'layouts/left_link_to_flights'
          a.btn.btn-info href="#{blogs_path}" type="button" style="width: 100%;"
            | More blog posts
          = render 'layouts/left_social_share'
    .col-md-8.col-md-offset-1.col-xs-12 style="background-color: white;"
      .posts-container
        h1 style="font-weight: bold;"
          = @post["title"]
        h3 style="margin-top: -20px; margin-bottom: 20px;"
          small
            = format_tumblr_date(@post["date"])
        .lead style="font-size: 18px;"
          = @post["body"].html_safe

javascript:
  $('.email-signup').toggle();
  $('#close-link').toggle();
  window.setTimeout(
    function(){
      $('#signup-link').toggle()
    },1000
  )
  