config/routes.rb
FlyShortcutRails::Application.routes.draw do
  match 'flights' => 'flights#index', as: :flights
  match 'filter' => 'flights#filter', as: :filter
  match 'visited' => 'flights#visited', as: :visited
  match 'about_us' => 'pages#about_us', as: :about_us
  match 'fbtest' => 'pages#fbtest', as: :fbtest
  match 'best_roundtrips' => 'pages#best_roundtrips', as: :best_roundtrips
  match 'offsite_flight' => 'offsite_flights#redirect', as: :offsite_flight
  match 'ga_test' => 'pages#ga_test', as: :ga_test
  match 'signups' => 'pages#signups', as: :signups
  post 'donate' => 'donations#donate', as: :donate
  get "routes-to-scrape" => "flights#routes_to_scrape", :as => :routes_to_scrape
  match 'blog' => 'blogs#index', as: :blogs
  get 'blog/:slug' => 'blogs#show', as: :blog
  resources :users, :only => [:create]
  resources :routes, :except => [:show]
  root :to => 'pages#index'

end

app/models/flight.rb
class Flight < ActiveRecord::Base
  attr_accessible :airline, :arrival_airport_id, :arrival_time, :departure_airport_id, :departure_time, :flight_no, :itinerary_id,
                  :price, :number_of_stops, :uid, :rid, :is_first_flight, :second_flight_destination, :second_flight_no,
                  :original_price, :origin_code, :shortcut, :pure_date, :cheapest_price, :epic, :month, :new

  belongs_to 	:itinerary,
  						:counter_cache => true

	belongs_to 	:departure_airport,
							:class_name => Airport,
							:foreign_key => 'departure_airport_id'

	belongs_to 	:arrival_airport,
							:class_name => Airport,
							:foreign_key => 'arrival_airport_id'

  def non_stop?
    number_of_stops == 0
  end

  def rounded_price
    (price / 100).round(0)
  end
end

app/controllers/flights_controller.rb
require 'csv'
require 'will_paginate/array'

class FlightsController < ApplicationController
  # http_basic_authenticate_with :name => ENV['ALLOWED_USER_NAME'], :password => ENV['ALLOWED_USER_PASSWORD'], :only => [:index]

  def index
    # Geomatch index
    geomatch_city = {
      "Chicago" => "MDW",
      "Dallas" => "DFW",
      "Fort Lauderdale" => "FLL",
      "Long Beach" => "LGB",
      "Los Angeles" => "LAX",
      "New York City" => "LGA",
      "Oakland" => "OAK",
      "Orlando" => "MCO",
      "San Diego" => "SAN",
      "San Jose" => "SJC"
    }

    geomatch_region = {
      "Alberta" => "YYC",
      "Arizona" => "PHX",
      "British Columbia" => "YVR",
      "California" => "SFO",
      "Colorado" => "DEN",
      "Florida" => "MIA",
      "Georgia" => "ATL",
      "Hawaii" => "HNL",
      "Illinois" => "ORD",
      "Maryland" => "BWI",
      "Massachusetts" => "BOS",
      "Michigan" => "DTW",
      "Nevada" => "LAS",
      "New Jersey" => "EWR",
      "New York" => "JFK",
      "North Carolina " => "CLT",
      "Ontario" => "YYZ",
      "Texas" => "IAH",
      "Virginia" => "IAD",
      "Washington" => "SEA",
      "Washington D.C." => "DCA"
    }

    # Seeing if there's a geocode match
    Geocoder.configure(:timeout => 3)
    request_data = request.location.data if request.location
    # request_data = Geocoder.search("74.212.154.18")[0].data # Test for Los Angeles
    # request_data = Geocoder.search("99.140.218.14")[0].data # Test for Illinois
    if request_data
      origin_code = geomatch_city[request_data["city"]]
      origin_code ||= geomatch_region[request_data["region_name"]]
    end

    # Else set the default
    origin_code ||= "SFO"
    origin_airport = Airport.find_by_code(origin_code)

    @user = User.new
    @airports = Airport.all.map { |airport| airport.name }.unshift("(Desired departure airport)")
    @empty_search = false

    params_to_send = {
      :password => ENV['POST_PASSWORD']
    }

    results = JSON.parse(RestClient.get "http://fs-#{origin_code.downcase}-api.herokuapp.com/flights", { :params => params_to_send })
    @flights = results["flights"]

    @from = [
      "Atlanta Hartsfield-Jackson ATL, GA (ATL)",
      "Baltimore Washington Int'l, MD (BWI)",
      "Boston Logan International, MA (BOS)",
      "Calgary International, AB (YYC)",
      "Charlotte Douglas, NC (CLT)",
      "Chicago Midway, IL (MDW)",
      "Chicago O'Hare, IL (ORD)",
      "Dallas/Ft Worth International, TX (DFW)",
      "Denver International, CO (DEN)",
      "Detroit Wayne County, MI (DTW)",
      "Fort Lauderdale International, FL (FLL)",
      "Honolulu International, HI (HNL)",
      "Houston George Bush Intercntl, TX (IAH)",
      "Las Vegas Mccarran International, NV (LAS)",
      "Long Beach Municipal, CA (LGB)",
      "Los Angeles International, CA (LAX)",
      "Miami International, FL (MIA)",
      "New York John F Kennedy International, NY (JFK)",
      "New York La Guardia, NY (LGA)",
      "New York Newark Liberty International, NJ (EWR)",
      "Oakland Metropolitan Oak International, CA (OAK)",
      "Orlando International, FL (MCO)",
      "Phoenix Sky Harbor Int'l, AZ (PHX)",
      "Ronald Reagan Washington Nat'l, DC (DCA)",
      "San Diego Lindberg Field, CA (SAN)",
      "San Francisco International, CA (SFO)",
      "San Jose Norman Y. Mineta International, CA (SJC)",
      "Seattle/Tacoma Sea/Tac, WA (SEA)",
      "Toronto Lester B Pearson, ON (YYZ)",
      "Vancouver International, BC (YVR)",
      "Washington Dulles International, DC (IAD)"
    ]
    @default_from = origin_airport.name
    @to = sort_destinations(results["destinations"])

    respond_to do |format|
      format.html
      format.json { render :json => { :combinations => @combinations, :from => @from, :to => @to } }
    end
  end

  def filter
    destination_name = params[:to]

    if params["segment"] == "Going"
      origin_airport = Airport.find_by_name(params[:from])
      origin_code = origin_airport.code

      params[:to] = params[:to] == "Any" ? 0 : Airport.find_by_name(params[:to]).id
      params[:from] = origin_airport.id
    else
      origin_airport = Airport.find_by_name(params[:to])
      origin_code = origin_airport.code

      params[:to] = Airport.find_by_name(params[:from]).id
      params[:from] = origin_airport.id

      @returning = true
    end


    params_to_send = {
      :password => ENV['POST_PASSWORD'],
      :passed_params => params
    }

    current_airports = [
      "ATL",
      "BOS",
      "BWI",
      "CLT",
      "DCA",
      "DEN",
      "DFW",
      "DTW",
      "EWR",
      "FLL",
      "HNL",
      "IAD",
      "IAH",
      "JFK",
      "LAS",
      "LAX",
      "LGA",
      "LGB",
      "MCO",
      "MDW",
      "MIA",
      "OAK",
      "ORD",
      "PHX",
      "SAN",
      "SEA",
      "SFO",
      "SJC",
      "YVR",
      "YYC",
      "YYZ"
    ]

    if current_airports.include?(origin_code)
      results = JSON.parse(RestClient.get "http://fs-#{origin_code.downcase}-api.herokuapp.com/filter", { :params => params_to_send })
      # results = JSON.parse(RestClient.get "http://localhost:3001/filter", { :params => params_to_send })
      @flights = results["flights"]

      destinations = sort_destinations(results["destinations"])

      @user = User.new
      @empty_search = @flights.empty? && !params[:scroll] ? true : false
      
      respond_to do |format|
        if @flights.any?
          format.json { render :json => { :flights => render_to_string('_flights.html.erb'), :destinations => destinations, :destination_name => destination_name } }
        elsif @empty_search
          format.json { render :json => { :flights => render_to_string('_flights.html.erb'), :destinations => destinations, :destination_name => destination_name, :noMoreFlights => true } }
        else
          format.json { render :json => { :flights => "<div class='no-more-flights label label-info'>No more flights to show</div>", :destinations => destinations, :destination_name => destination_name, :noMoreFlights => true } }
        end
      end
    else
      respond_to do |format|
        @empty_search = true
        format.json { render :json => { :flights => render_to_string('_flights.html.erb'), :destinations => [], :destination_name => "", :noMoreFlights => true } }
      end
    end
  end

  def routes_to_scrape
    respond_to do |format|
      if params[:password] == ENV['POST_PASSWORD']
        routes = []
        Dir[Rails.root.join("db/routes/#{params[:code]}/*.csv")].each do |file|
          CSV.foreach(file) do |route|
            routes << [route[0], route[1]]
          end
        end
        format.json { render :json => { "routes" => routes.uniq } }
      else
        format.json { render :json => { "message" => "Whatcha tryin' to pull?" } }
      end
    end
  end

  def visited
    session[:visited] = true
    respond_to do |format|
      format.json { render :json => "Done" }
    end
  end

  private

  def sort_destinations(arr)
    arr.map{ |airport_id| Airport.find(airport_id).name }.sort.unshift("Any")
  end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_art.html.erb
<!--
                                           ********
                                          *      *
                                         *      *
      ***********************************      *
    *  (  )      () () () () () ()            *
  *           *        *                   *
 *             *        *               *
  *************************************
                  *       *
                   *********

Hello there! Looks like you found out where we store the shortcut data! Alright, you can have it for free, since you're so clever :) -->

app/views/flights/_date_pickers.html.slim
div
  .hidden-sm
    label.going-label for="daterange"
      | Going
  .input-prepend
    .btn-group.date-group
      button.btn.btn-success.going-button type="button"
        | Showing
      input#daterange.date-input-field name="daterange" placeholder="Select departure date range" type="text"
.to-field-holder.returning-filters
  .hidden-sm
    label.returning-label for="daterange-return"
      | Returning
  .input-prepend
    .btn-group.date-group
      button.btn.btn-success.returning-button type="button"
        | Click to show
      input#daterange-return.date-input-field.opensright name="daterange-return" placeholder="Select returning date range" type="text"

app/views/flights/_flights.html.slim
- if !@empty_search
  - @flights.each do |flight|
    - flight = format_flight(flight)
    - departure_airport = Airport.find(flight["departure_airport_id"])
    - arrival_airport = Airport.find(flight["arrival_airport_id"])
    - shortcut_airport = Airport.find(flight['second_flight_destination'])
    - if departure_airport
      .hero-unit
        / .social-buttons
        /   javascript:
        /     function popupwindow(url, title, w, h) {
        /       var left = (screen.width/2)-(w/2);
        /       var top = (screen.height/2)-(h/2);
        /       return window.open(url, title, 'toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no, width='+w+', height='+h+', top='+top+', left='+left);
        /     }

        /   - epic = flight["epic"] ? "an%20%23epic%20flight" : "a%20flight"
        /   - message = "What%3F!%20I%20just%20found%20#{epic}%20from%20%23#{departure_airport.code}%20to%20%23#{arrival_airport.code}%20for%20%24#{rounded_price(flight['price'])}!&tw_p=tweetbutton&url=http%3A%2F%2Fflyshortcut.com"
        /   - link = "https://twitter.com/intent/tweet?hashtags=flyshortcut%2Ctravel&text=#{message}"
        /   / .fb-share-button data-href="http://www.flyshortcut.com/flights" data-type="icon" data-width="30px"
        /   a href="https://www.facebook.com/sharer/sharer.php?u=http://www.flyshortcut.com/flights" target="_blank" onclick="popupwindow('https://www.facebook.com/sharer/sharer.php?u=http://www.flyshortcut.com/flights', 'Share this Shortcut', '550', '550'); return false;"
        /     i.fa.fa-facebook-square
        /   a href="#{link}"
        /     i.fa.fa-twitter-square
        .top-half
          .price
            = "$#{rounded_price(flight['price'])}"
          - if flight["epic"]
            .epic-word.label.label-warning
              | EPIC
          .flight-title
            .label.label-info
              = "#{departure_airport.code}"
            i.fa.fa-long-arrow-right style="font-size: 20px !important;"
            .label.label-info
              = "#{arrival_airport.code}"
        .bottom-half
          ruby: 
            str = "Save "
            if flight["epic"]
              pure_search_params = {
                :pure_search => true,
                :departure_airport_id => flight["departure_airport_id"],
                :departure_time => flight["departure_time"],
                :arrival_airport_id => flight["arrival_airport_id"],
                :airline => flight["airline"],
                :flight_no => flight["flight_no"]
              }
              cheapest_price_calc = (flight['cheapest_price'] - flight['price']) / 100 + 1
              str += "<strong>$#{cheapest_price_calc}</strong>"
              #str += " off the #{link_to 'cheapest flight', offsite_flight_path(pure_search_params), :target => '_blank'} of the day, and "
              str += " off the cheapest flight of the day, and "
            end
            original_params = {
              :original => true,
              :departure_airport_id => flight["departure_airport_id"],
              :departure_time => flight["departure_time"],
              :arrival_airport_id => flight["arrival_airport_id"],
              :airline => flight["airline"],
              :flight_no => flight["flight_no"]
            }
            original_price_calc = (flight['original_price'] / 100 + 1) - rounded_price(flight['price'])
            str += "<strong>$#{original_price_calc}</strong>"
            #str += " off the #{link_to 'original flight', offsite_flight_path(original_params), :target => '_blank'}"
            str += " off the original flight"
          .below-table
            .savings-calc style="margin: 5px 0px 15px 0px;" data-mobile-url="#{mobile_url(departure_airport.code, arrival_airport.code, flight['departure_time'])}"
              - if flight["epic"]
                .savings-buffer.hidden-xs
              = str.html_safe
          .row
            ruby:
              book_params = {
                :original => false,
                :departure_airport_id => flight["departure_airport_id"],
                :departure_time => flight["departure_time"],
                :second_flight_destination => flight["second_flight_destination"],
                :airline => flight["airline"],
                :flight_no => flight["flight_no"]
              }
              flight_itinerary = "#{departure_airport.code} → #{arrival_airport.code}"
              departure_city_in_words = "#{departure_airport.city} (#{departure_airport.code})"
              departure_time_in_words = "#{flight["departure_time"].strftime('%b %d, %Y')} at #{flight["departure_time"].strftime("%l:%M %p")}"
              arrival_city_in_words = "#{arrival_airport.city} (#{arrival_airport.code})"
              arrival_time_in_words = "#{flight["arrival_time"].strftime('%b %d, %Y')} at #{flight["arrival_time"].strftime("%l:%M %p")}"
              flight_number_in_words = "Flight: #{flight['airline']} #{flight['flight_no']}"
            / a href="#{offsite_flight_path(book_params)}" target="_blank"
            /   button.btn.btn-success.btn-large.book-button data-content="Find #{flight['airline']} #{flight['flight_no']} connecting on to #{shortcut_airport.name}. Have fun, and remember to read about the risks before you shortcut!" onClick="_gaq.push(['_trackEvent', 'button', 'click', 'Book: #{departure_airport.code}-#{arrival_airport.code}']);" title="Book the flight" type="submit" data-mobile-url="#{mobile_url(departure_airport.code, shortcut_airport.code, flight['departure_time'])}"
            /     | Book
              
            .col-sm-4
              strong
                | Depart
              .flight-detail
                div
                  = departure_city_in_words
                div
                  = departure_time_in_words
                div
                  = "Flight: #{flight['airline']} #{flight['flight_no']}"

            .col-sm-4
              strong
                | Arrive
              .flight-detail
                div
                  = arrival_city_in_words
                div
                  = arrival_time_in_words
              i.glyphicon.glyphicon-circle-arrow-right.flight-arrow.right-arrow-normal

            .col-sm-4
              strong
                | Skip this flight
              .shortcut-flight
                = render "flights/art.html.slim"
                button.btn.btn-success.btn-large.pay-button data-toggle="modal" data-cheapest-price="#{flight['cheapest_price'] / 100 + 1}" data-shortcut-price="#{rounded_price(flight['price'])}" data-shortcut-airport="#{shortcut_airport.city}" data-shortcut-airport-code="#{shortcut_airport.code}" data-itinerary="#{flight_itinerary}" data-flight-number="#{flight_number_in_words}" data-departure-time="#{departure_time_in_words}" data-arrival-time="#{arrival_time_in_words}" data-ga-airport-tracking="#{departure_airport.code}-#{arrival_airport.code}" data-offsite-link="#{offsite_flight_path(book_params)}" data-offsite-original-link="#{offsite_flight_path(pure_search_params)}"
                  | Show flight
                / div
                /   = "#{shortcut_airport.city} (#{shortcut_airport.code})"
                / div
                /   | Don't take this flight :)
              = image_tag("cut-icon.png", :width => "90%", :class => "flight-arrow right-arrow-shortcut circle")


- else
  .hero-unit.no-flights
    h2
      | Ermahgerd! No flights?
    div
      h3
        | 1. Try adjusting your filters.
    div
      h3
        | 2. Still no luck?
        a.empty-results-signup href="#"
          = " Sign up "
        | for notifications on new routes!
    - if @returning
      div
        | Note: If you already have a shortcut flight going to your destination, you're already going to pay less than you would have if you booked a traditional roundtrip ticket. Even if you buy a normal returning one-way ticket, you'll still win.

app/views/flights/_redirect.html.erb
<div id="overlay" class="hide"></div>
<div class="redirect-box hide">
  <h4>Redirecting you to travelocity...</h4>
  <%= image_tag 'loading.gif' %>
  <div class="redirect-text">Another tab will open with your results shortly</div>
  <a href="#" id="generated-link" target="_blank"><a>
</div>

app/views/flights/index.html.slim
/ Facebook share
#fb-root
javascript:
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=651908141502421";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

.container#flight-page
  .row
    .col-md-3.col-xs-12
      .row.header-column
        .col-xs-12 style="text-align: center;"
          = render 'layouts/header'
        .col-sm-5.col-sm-offset-1.col-md-12
        	= render 'layouts/city_selector'
        .hidden-xs.col-sm-6.col-md-12.btn-group.segment data-toggle="buttons-radio"
          = render 'date_pickers'
        .col-xs-12
          / = render 'layouts/donate'
    .col-md-8.col-md-offset-1.col-xs-12.all-flights
      div
        = render 'layouts/alerts'
      div
      	= render 'layouts/top_filter'
      .loading.hide
        = image_tag "loading.gif"
      = render 'flights'

/ = render "layouts/donate_modal"
= render "layouts/pay_modal"
/ = render "layouts/system_down_modal"

app/views/flights/search.html.erb
<div id="top"></div>
<div class="container">
  <div class="row intro">
    <div class="span12">
      Hi Adrian
      <button type="button" class="btn btn-primary loading" data-loading-text="Loading...">See Shortcut Flights</button>
    </div>
  </div>

  <% if @flights %>

  <div class="row">
    <div class="span3">
      <%= render 'layouts/filter' %>
    </div>

    <div class="span8 offset1">
      <% @flights.each do |flights_array| %>
      <% flight = flights_array[0] %>
      <% non_stop = flights_array[1] %>
      <% non_stop.rounded_price %>
      <% flight.rounded_price %>

      <div class="hero-unit origin<%= flight.departure_airport_code %> destination<%= flight.arrival_airport_code %> <%= flight.departure_time.to_date %>">

        <div class="top-half">
          <div class="price">$<%= flight.rounded_price %></div>
          <div class="savings">Save <strong>$<%= non_stop.rounded_price - flight.rounded_price %></strong> off the <%= link_to "original flight", offsite_flight_path(flight, original: true) %></div>
        </div>

        <div class="bottom-half">
          <table>
            <tr>
              <td class="label label-info">Depart</td>
              <td><%= flight.departure_airport_name %></td>
              <td><%= flight.departure_time.strftime('%B %d, %Y') %></td>
              <td><%= flight.departure_time.strftime("%I:%M%p") %></td>
            </tr>
            <tr>
              <td class="label label-info">Arrive</td>
              <td><%= flight.arrival_airport_name %></td>
              <td><%= flight.arrival_time.strftime('%B %d, %Y') %></td>
              <td><%= flight.arrival_time.strftime("%I:%M%p") %></td>
            </tr>
          </table>
          <div class="below-table">
            <a href="<%= offsite_flight_path(flight, original: false) %>"><button type="submit" class="btn btn-success btn-large">Book</button></a>

            <div class="flight-no"><%= flight.airline %> Flt: <%= flight.flight_no %></div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>

  <% end %>

</div>
<div id="bot"></div>