config/routes.rb
FlyShortcutRails::Application.routes.draw do
  match 'flights' => 'flights#index', as: :flights
  match 'filter' => 'flights#filter', as: :filter
  match 'visited' => 'flights#visited', as: :visited
  match 'about_us' => 'pages#about_us', as: :about_us
  match 'fbtest' => 'pages#fbtest', as: :fbtest
  match 'best_roundtrips' => 'pages#best_roundtrips', as: :best_roundtrips
  match 'offsite_flight' => 'offsite_flights#redirect', as: :offsite_flight
  match 'ga_test' => 'pages#ga_test', as: :ga_test
  match 'signups' => 'pages#signups', as: :signups
  post 'donate' => 'donations#donate', as: :donate
  get "routes-to-scrape" => "flights#routes_to_scrape", :as => :routes_to_scrape
  match 'blog' => 'blogs#index', as: :blogs
  get 'blog/:slug' => 'blogs#show', as: :blog
  resources :users, :only => [:create]
  resources :routes, :except => [:show]
  root :to => 'pages#index'

end

app/models/route.rb
class Route < ActiveRecord::Base
  attr_accessible :origin_airport_id, :destination_airport_id, :cheapest_price, :date
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  http_basic_authenticate_with :name => ENV['ADMIN_NAME'], :password => ENV['ADMIN_PASSWORD']

  def index
    @routes = Route.order("origin_airport_id ASC")
  end

  def new
    @route = Route.new
  end

  def create
    convert_airport_ids_to_code
    convert_price_to_integer
    @route = Route.new(params[:route])
    if @route.save
      flash[:success] = "#{Airport.find(@route.origin_airport_id).code} - #{Airport.find(@route.destination_airport_id).code} has been successfully created."
      redirect_to routes_path
    else
      flash.now[:warning] = "Gawd. Fill everything in correctly man."
      render "new"
    end
  end

  def edit
    @route = Route.find(params[:id])
  end

  def update
    convert_airport_ids_to_code
    convert_price_to_integer
    @route = Route.find(params[:id])
    @route.assign_attributes(params[:route])
    if @route.save
      flash[:success] = "#{Airport.find(@route.origin_airport_id).code} - #{Airport.find(@route.destination_airport_id).code} has been successfully updated."
      redirect_to routes_path
    else
      flash.now[:warning] = "Gawd. Fill everything in correctly man."
      render "edit"
    end
  end

  def destroy
    route = Route.find(params[:id]).destroy
    flash[:success] = "#{Airport.find(route.origin_airport_id).code} - #{Airport.find(route.destination_airport_id).code} has been deleted."
    redirect_to routes_path
  end

  private

  def convert_airport_ids_to_code
    params[:route][:origin_airport_id] = Airport.find_by_code(params[:route][:origin_airport_id]).id
    params[:route][:destination_airport_id] = Airport.find_by_code(params[:route][:destination_airport_id]).id
  end

  def convert_price_to_integer
    params[:route][:cheapest_price] = (params[:route][:cheapest_price].to_f * 100).to_i
  end
end

app/views/routes/_form.html.slim
= simple_form_for @route, :url => url_for(:action => "#{@route.id ? 'update' : 'create'}", :controller => "routes") do |f|
  .form-group
    label for="route_origin_airport_id"
      b Origin airport
    = f.text_field :origin_airport_id, :value => "#{@route.origin_airport_id ? Airport.find(@route.origin_airport_id).code : nil}", :class => "form-control"

  .form-group
    label for="route_destination_airport_id"
      b Destination airport
    = f.text_field :destination_airport_id, :value => "#{@route.destination_airport_id ? Airport.find(@route.destination_airport_id).code : nil}", :class => "form-control"

  .form-group
    label for="route_cheapest_price"
      b Cheapest price
    = f.text_field :cheapest_price, :value => "#{@route.cheapest_price ? @route.cheapest_price / 100 : nil}", :class => "form-control"

  br

  button.btn.btn-success type="submit"
    = "#{Route.find_by_id(@route.id) ? "Save" : "Create"}"

  br
  br
  br

  - if Route.find_by_id(@route.id)
    div style="padding: 10px 5px;"
      = link_to "Delete", { :id => @route.id, :action => :destroy }, :method => :delete, :confirm => "You know what you're doing right?  You're about to delete this route..."

app/views/routes/edit.html.slim
h2
  | Edit route

= render "form"

app/views/routes/index.html.slim
#flash
  - flash.each do |name, msg|
    = content_tag :div, msg, :id => "flash_#{name}", class: "alert alert-#{name}"

h2
  | All routes
  .pull-right
    = link_to("Create", new_route_path, :class => "btn btn-primary")

table.table
  tr
    th
      | Origin
    th
      | Destination
    th
      | Price
    th
      | Edit

  - @routes.each do |route|
    tr
      td
        = Airport.find(route.origin_airport_id).code
      td
        = Airport.find(route.destination_airport_id).code
      td
        = number_to_currency(route.cheapest_price / 100)
      td
        = link_to("Edit", edit_route_path(route))

app/views/routes/new.html.slim
h2
  | New route

= render "form"