config/routes.rb
FlyShortcutRails::Application.routes.draw do
  match 'flights' => 'flights#index', as: :flights
  match 'filter' => 'flights#filter', as: :filter
  match 'visited' => 'flights#visited', as: :visited
  match 'about_us' => 'pages#about_us', as: :about_us
  match 'fbtest' => 'pages#fbtest', as: :fbtest
  match 'best_roundtrips' => 'pages#best_roundtrips', as: :best_roundtrips
  match 'offsite_flight' => 'offsite_flights#redirect', as: :offsite_flight
  match 'ga_test' => 'pages#ga_test', as: :ga_test
  match 'signups' => 'pages#signups', as: :signups
  post 'donate' => 'donations#donate', as: :donate
  get "routes-to-scrape" => "flights#routes_to_scrape", :as => :routes_to_scrape
  match 'blog' => 'blogs#index', as: :blogs
  get 'blog/:slug' => 'blogs#show', as: :blog
  resources :users, :only => [:create]
  resources :routes, :except => [:show]
  root :to => 'pages#index'

end

app/views/layouts/_alerts.html.slim
- unless session[:visited]
  .alert.first-time-here
    a.close.learn-more-close data-dismiss="alert" href="#"
      | &times;
    .row
      .col-sm-8
        h4 First time here?
        strong
          | We're not your average flight search engine.
      .col-sm-4.hidden-xs
        a.learn-more-link href="/#panel2"
          | Learn more
    .row.first-time-here-content
      .col-xs-12.explanation-image
        = image_tag "panel3image.png", :width => "100%"
      .col-xs-12.visible-xs
        a.learn-more-link href="/#panel2"
          | Learn more
.alert.email-signup
  a.close href="#"
    | &times;
  div
    h4 100% epic travel hacks. 0% spam.
  .flash.hide.initial-flash
    - flash.each do |name, msg|
      = content_tag :div, msg, :id => "flash_#{name}", class: "alert alert-#{name}"
  .initial-email.initial-email-content
    form
      .row
        .col-sm-4
          input#initial-email name="user[email]" placeholder="Email" type="text"
        .col-sm-4
          = select_tag "all-airports", options_for_select(@airports), :class => "selectpicker", "data-live-search" => "true", "data-width" => "100%"
        .col-sm-4
          a.initial-signup-button href="#"
            | Subscribe

app/views/layouts/_city_selector.html.erb
<div class="row city-holder" style="text-align: left;">
  <div class="from-airport col-xs-2">
    <span><label for="from-dropdown" class="label label-info">From</label></span>
  </div>
  <div class="from-airport col-xs-10">
    <%= select_tag "from-dropdown", options_for_select(@from, :selected => @default_from), :class => "selectpicker", "data-live-search" => "true", "data-width" => "100%" %>
  </div>
  <div class="to-airport">
    <div class="to-airport col-xs-2">
      <span><label for="to-dropdown" class="label label-info to-label">To</label></span>
    </div>
    <div class="to-airport col-xs-10">
      <%= select_tag "to-dropdown", options_for_select(@to), :class => "selectpicker", "data-live-search" => "true", "data-width" => "100%" %>
    </div>
  </div>
</div>

app/views/layouts/_donate_modal.html.slim
script src="https://checkout.stripe.com/v2/checkout.js"

#donateModal.modal.fade aria-hidden="true" aria-labelledby="donateModalLabel" role="dialog" tabindex="-1"
  .modal-dialog
    .modal-content

      .modal-header
        button.close aria-hidden="true" data-dismiss="modal" type="button"
          | &times;
        h2#donateModalLabel.modal-title
          | Thank you

        h3 style="margin-top: -5px;"
          small
            | We hope you saved some money :)

      .modal-body
        .row.hide-after-payment
          .col-xs-12.col-sm-6
            .input-group
              span.input-group-addon
                | $
              input#custom-donation.form-control type="number" placeholder="Beer ~= $5"
              .input-group-btn
                button#stripeDonateButton.btn.btn-primary
                  | Donate

            form.donation-form action="#{donate_path}" method="post" data-stripe-pk="#{Rails.configuration.stripe[:publishable_key]}"

          .col-xs-12
            p style="margin: 20px 0; font-style: italic;"
              | - or -
            p
              i.fa.fa-bitcoin style="margin-right: 3px;"
              span style="font-size: 12px;"
                | 1zM6QtMeC4jDjz4k1A6qGhVU2Bx5f6Sno

        .row.show-after-payment style="display: none;"
          .col-xs-12
            h4
              .donation-processing-message
                div style="margin: 20px 0;"
                  | Processing the donation (and thinking about what beer to drink)...
                div
                  = image_tag 'loading.gif'

              .donation-message

app/views/layouts/_email.html.erb
<%= form_for @user, :remote => true do |f| %>
  <%= f.text_field :email, :placeholder => "Email", :id => "email" %>
  <%= f.submit "Sign up", :class => "btn btn-success", :id => "email-button" %>
<% end %>

app/views/layouts/_filter.html.erb
<div class="top-bar">
	<div class="navbar">
		<ul class="nav">
      <form class="form-inline">
      	<div class="input-prepend">
	      	<!-- <span class="add-on"><p>From:</p></span> -->
	      	<div><label for="from-dropdown">From:</label></div>
	      	<%= select_tag "from-dropdown", options_for_select(@from) %>
				  <!-- <input type="text" class="input-large" id="origin"placeholder="Where you are..."> -->
				</div>
				<div class="input-prepend">
			  	<!-- <span class="add-on">To:</span> -->
			  	<div><label for="to-dropdown">To:</label></div>
			  	<%= select_tag "to-dropdown", options_for_select(@to) %>
			  	<!-- <input type="text" class="input-large" id="destination" placeholder="Where you wanna go..."> -->
				</div>
				<div>
			  	<button type="submit" class="btn btn-info btn-large">Filter</button>
			  <div>
			</form>
  	</ul>
	</div>
</div>

app/views/layouts/_flight_stats.html.erb
<table class="stats">
  <tr class="stats-header">
    <th class="stats-route">Route</th>
    <th class="stats-num">Epic</th>
    <th class="stats-num">All</th>
    <th class="stats-savings">Cheapest</th>
  </tr>
  <% @stats.sort.each do |route, stats| %>
    <tr>
      <td><%= route %></td>
      <td class="stats-num"><%= stats[0] %></td>
      <td class="stats-num"><%= stats[1] %></td>
      <td class="stats-savings"><%= number_to_currency(stats[2] / 100, :precision => 0) %></td>
    </tr>
  <% end %>
  <tr class="stats-last-row">
    <td>Total:</td>
    <td class="stats-num"><%= @epic %></td>
    <td class="stats-num"><%= @all %></td>
    <td class="stats-savings"></td>
  </tr>
</table>

app/views/layouts/_footer.html.erb
<footer>
	<p>&copy; <%= Time.now.year %> FlyShortcut
    <script src='http://connect.facebook.net/en_US/all.js'></script>
  </p>
  <div id='fb-root'>
    <!-- <a href="#" class="fb-button"><%= image_tag "facebook_button.png", :width => 76 %></a> -->
  </div>
</footer>

app/views/layouts/_header.html.erb
<div id="logo">
	<a href="/"><img src="/img/flyshortcut_logo_with_tagline_transparent.png"></a>
</div>
<div class="header-links">
  <!-- <%= link_to "About", "/#panel2" %> ⋅ <a id="signup-link" class="hidden" href="#" title="Sign up" data-content="We will let you know about new routes and really big epic wins!">Sign up for alerts</a><a id="close-link" href="#">Close sign up box</a> ⋅ <%= mail_to('david@dwakventures.com', "Contact", :cc => 'adrian@dwakventures.com', :encode => "hex", :subject => "From FlyShortcut", :class => 'contact-us', :target => "_blank") %> -->
  <%= link_to "About", "/#panel2" %> ⋅ <%= link_to "Blog", "/blog" %> ⋅ <a id="signup-link" class="hidden" href="#" title="Sign up" data-content="We will let you know about new routes and really big epic wins!">Sign up for alerts</a><a id="close-link" href="#">Close sign up box</a> ⋅ <%= mail_to('dstwen@outlook.com', "Contact", :encode => "hex", :subject => "From FlyShortcut", :class => 'contact-us', :target => "_blank") %>
</div>

app/views/layouts/_left_email.html.slim
div style="text-align: left; margin-bottom: 10px;"
  .alert.email-signup style="margin: 0; margin-top: 20px;"
    a.close href="#"
      | &times;
    div
      h4 style="margin-top: 10px;"
        | Sign up for alerts
    .flash.hide.initial-flash
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}", class: "alert alert-#{name}"
    .initial-email.initial-email-content
      form
        .row
          .col-sm-12
            = select_tag "all-airports", options_for_select(@airports), :class => "selectpicker", "data-live-search" => "true", "data-width" => "100%"
          .col-sm-12
            input#initial-email name="user[email]" placeholder="Email" type="text" style="margin-bottom: 10px;"
          .col-sm-12
            a.initial-signup-button href="#"
              | Submit

app/views/layouts/_left_link_to_flights.html.slim
a.btn.btn-primary href="#{flights_path}" type="button" style="width: 100%; margin: 10px 0;"
  | Find flights

app/views/layouts/_left_social_share.html.slim
.row
  - message = "#{@post ? @post['title'] : 'Check out this post on FlyShortcut'}&tw_p=tweetbutton&url=#{request.original_url}"
  - link = "https://twitter.com/intent/tweet?hashtags=flyshortcut%2Ctravel&text=#{message}"
  .col-xs-6 style="padding-right: 10px;"
    a.blog-share-button href="https://www.facebook.com/sharer/sharer.php?u=#{request.original_url}" target="_blank"
      .social-content-holder
        span
          i.fa.fa-facebook-square.fa-2x.social-icon
        span
          = " Share"
  .col-xs-6 style="padding-left: 10px;"
    a.blog-share-button href="#{link}"
      .social-content-holder
        span
          i.fa.fa-twitter.fa-2x.social-icon
        span
          = " Tweet"

app/views/layouts/_pay_modal.html.slim
script src="https://checkout.stripe.com/v2/checkout.js"

#payModal.modal.fade aria-hidden="true" aria-labelledby="payModalLabel" role="dialog" tabindex="-1" data-shortcut-destination=""
  .modal-dialog
    .modal-content
      .modal-header
        .row style="text-align: center;"
          .col-xs-12
            button.close aria-hidden="true" data-dismiss="modal" type="button"
              | &times;
            h2#donateModalLabel.modal-title
              | SFO → ORD

            h3 style="margin-top: -5px;"
              small#pay-flight-number
                | Flight: American Airlines 1240
            h3 style="margin-top: -15px;"
              small#pay-flight-departure
                | Depart: Jun 30, 2014 at 9:15 AM
            h3 style="margin-top: -15px;"
              small#pay-flight-arrival
                | Arrive: Jun 30, 2014 at 11:18 AM

      .modal-body
        .row.hide-after-payment
          .col-xs-12.col-sm-6
            .panel.panel-info
              .panel-heading
                h3.panel-title
                  | How it works
              .panel-body
                / | FlyShortcut will show you which city to book to for a fee equivalent to 25% of your flight savings. After the payment is made, the destination airport will be displayed. If for some reason you cannot find the flight that we show, please email us immediately and we will try to find it or refund you right away.
                | Once you share FlyShortcut on Facebook, we will show you which city to book to to get these savings. You will have one week of unlimited access to this information (we gave you three views so far). If for some reason you cannot find the flight that we show, please email us immediately and we will try to help you find it.

          .col-xs-12.col-sm-6
            table.table
              tbody
                tr
                  td.no-border-cell
                    a#pay-cheapest-offsite-link href="#" target="_blank"
                      | Cheapest same-day flight:
                  td.no-border-cell#pay-cheapest-price
                    | $200
                tr
                  td.no-border-cell
                    | Shortcut flight:
                  td.no-border-cell#pay-shortcut-price
                    | $150
                tr
                  td.highlighted-cell
                    b
                      | Shortcut savings:
                  td.highlighted-cell
                    b#pay-shortcut-savings
                      | $50

                / tr
                /   td.no-border-cell
                /     | Shortcut fee:
                /   td.no-border-cell
                /     | x 25%
                / tr
                /   td.highlighted-cell
                /     b
                /       | Amount to pay:
                /   td.highlighted-cell
                /     b#pay-shortcut-fee
                /       | $12.50

                / tr
                /   td.super-highlighted-cell
                /     b
                /       | You still save:
                /   td.super-highlighted-cell
                /     b#pay-still-save
                /       | $37.50

            .row style="text-align: center;"
              javascript:
                function popupwindow(url, title, w, h) {
                  var left = (screen.width/2)-(w/2);
                  var top = (screen.height/2)-(h/2);
                  return window.open(url, title, 'toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no, width='+w+', height='+h+', top='+top+', left='+left);
                }

              .col-xs-12
                h5
                  | Share to unlock
              .col-xs-12
                a#facebook-share-link.social-share-button href="https://www.facebook.com/sharer/sharer.php?u=http://www.flyshortcut.com/flights" target="_blank" onclick="popupwindow('https://www.facebook.com/sharer/sharer.php?u=http://www.flyshortcut.com/flights', 'Share this Shortcut', '550', '550'); return false;"
                  button.btn.btn-primary style="margin-right: 10px;"
                    i.fa.fa-facebook
                    = "  Facebook"
                / a#twitter-share-link.social-share-button href=""
                /   button.btn.btn-primary
                /     i.fa.fa-twitter
                /     = "  Twitter"
              .col-xs-12
                button.btn.btn-warning.confirm-share style="display: none;"
                  | Confirm share

              / .col-xs-12
              /   button#stripeDonateButton.btn.btn-primary
              /     | Pay to see shortcut destination
              /   form.donation-form action="#{donate_path}" method="post" data-stripe-pk="#{Rails.configuration.stripe[:publishable_key]}"

        .row style="text-align: center;"
          .col-xs-12
            h4
              .donation-message

        .row.donation-processing-message style="display: none;"
          .col-xs-12
            h4 style="text-align: center;"
              div style="margin: 20px 0;"
                | Processing the payment - please wait...
              div
                = image_tag 'loading.gif'

        .row.show-after-payment style="display: none;"
          .col-xs-12
            .pay-booking-instructions
              / .panel.panel-info style="margin-top: 30px;"
              .panel.panel-info
                .panel-heading
                  h3.panel-title
                    | Booking instructions

                .panel-body
                  .shortcut-instructions style="margin-bottom: 20px;"
                  a#pay-offsite-link href="#" target="_blank"
                    button.btn.btn-success.btn-large
                      | Book

                  / button.btn.btn-default.close-pay-modal data-content="Remember to copy down the above information. Once you close this window the information will be erased." style="margin-left: 10px;"
                  button.btn.btn-default.close-pay-modal style="margin-left: 10px;"
                    | Close

app/views/layouts/_system_down_modal.html.slim
#systemDownModal.modal.fade aria-hidden="true" aria-labelledby="payModalLabel" role="dialog" tabindex="-1" data-shortcut-destination=""
  .modal-dialog
    .modal-content
      .modal-header
        .row style="text-align: center;"
          .col-xs-12
            button.close aria-hidden="true" data-dismiss="modal" type="button"
              | &times;
            h2#donateModalLabel.modal-title
              | Unfortunately, we're having some issues with our data

      .modal-body
        .row.hide-after-payment
          .col-xs-12
            | Some of our data appear a little off. Please be patient with us while we work on a fix!

app/views/layouts/_top_filter.html.erb
<div class="toggle-buttons">
  <div class="type-filter">
    <div>Type:</div>
    <div class="btn-group filter-type" data-toggle="buttons-radio">
      <button type="button" class="btn btn-info filter" id="epic-button" title="Epic flights" data-content="These flights are at least $20 cheaper than the same flight being sold on traditional search engines">Epic</button>
      <button type="button" class="btn btn-info filter">All</button>
    </div>
  </div>
  <div class="sort-filter">
    <div>Sort by:</div>
    <div class="btn-group filter-sort" data-toggle="buttons-radio">
      <button type="button" class="btn btn-info filter">Price</button>
      <button type="button" class="btn btn-info filter">Time</button>
    </div>
  </div>
</div>